apiVersion: v1
kind: Service
metadata:
  name: serving-pipeline-backend-service
  namespace: nexusml # Assuming a namespace for the project
spec:
  selector:
    app: serving-pipeline-backend # Matches the labels in the Deployment template
  ports:
  - protocol: TCP
    port: 8000 # Port the backend service listens on
    targetPort: 8000
    name: backend-port
  type: ClusterIP # Default type, accessible within the cluster
