apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nexusml
spec:
  selector:
    app: frontend
  ports:
  - name: web
    protocol: TCP
    port: 7860
    targetPort: 7860
    nodePort: 30860
  type: LoadBalancer
