apiVersion: v1
kind: Service
metadata:
  name: serving-pipeline-frontend-service
  namespace: nexusml # Assuming a namespace for the project
spec:
  selector:
    app: serving-pipeline-frontend # Matches the labels in the Deployment template
  ports:
  - protocol: TCP
    port: 3000 # Port the frontend service listens on
    targetPort: 3000
    name: frontend-port
  type: ClusterIP # Default type, accessible within the cluster
