apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: nexusml
type: Opaque
data:
  MINIO_ROOT_USER: bWluaW8tYWNjZXNzLWtleQ== # base64: "minio-access-key"
  MINIO_ROOT_PASSWORD: bWluaW8tc2VjcmV0LWtleQ== # base64: "minio-secret-key"
