apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: nexusml # Assuming a namespace for the project
spec:
  selector:
    app: grafana # Matches the labels in the Deployment template
  ports:
  - protocol: TCP
    port: 3000 # Port Grafana listens on
    targetPort: 3000
    name: grafana-port
  type: ClusterIP # Default type, accessible within the cluster
