apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: nexusml # Assuming a namespace for the project
spec:
  selector:
    app: prometheus # Matches the labels in the StatefulSet template
  ports:
  - protocol: TCP
    port: 9090 # Port Prometheus listens on
    targetPort: 9090
    name: prometheus-port
  type: ClusterIP # Default type, accessible within the cluster
