apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: nexusml # Assuming a namespace for the project
spec:
  selector:
    app: kafka # Matches the labels in the StatefulSet template
  ports:
  - protocol: TCP
    port: 9092 # Port Kafka listens on
    targetPort: 9092
    name: kafka-port
  clusterIP: None # Headless service for StatefulSet discovery
