apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pipeline-consumer-storage # Example name, adjust if needed
  namespace: nexusml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust storage size as needed for consumer data
