apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pipeline-crawler-storage # Example name, adjust if needed
  namespace: nexusml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust storage size as needed for crawler data
