apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nexusml # Assuming a namespace for the project
type: Opaque
# data:
#   POSTGRES_USER: cG9zdGdyZXM= # base64 encoded "postgres"
#   POSTGRES_PASSWORD: YWl2bjIwMjU= # base64 encoded "aivn2025"
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:aivn2025@postgres-service.nexusml.svc.cluster.local:5432/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:aivn2025@postgres-service.nexusml.svc.cluster.local:5432/airflow