apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nexusml # Assuming a namespace for the project
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded "postgres"
  POSTGRES_PASSWORD: YWl2bjIwMjU= # base64 encoded "aivn2025"
stringData:
