apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: nexusml # Assuming a namespace for the project
spec:
  selector:
    app: loki # Matches the labels in the StatefulSet template
  ports:
  - protocol: TCP
    port: 3100 # Port Loki listens on
    targetPort: 3100
    name: loki-port
  clusterIP: None # Headless service for StatefulSet discovery
