apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: nexusml
spec:
  replicas: 2                                 # 2 worker là tối ưu cho node 4-core
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsUser: 50000
        runAsGroup: 50000
        fsGroup: 50000                        # fix quyền ghi logs/dags
      containers:
      - name: airflow-worker
        image: nbngoc1303/airflow-image:latest
        imagePullPolicy: Always
        command: ["airflow", "celery", "worker"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"                         # cực thấp → không bao giờ Pending nữa
          limits:
            memory: "6Gi"
            cpu: "3000m"                        # task ML nặng vẫn dùng được
        livenessProbe:
          exec:
            command: ["celery", "-A", "airflow.executors.celery_executor", "inspect", "ping"]
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        env:
          - name: AIRFLOW__CORE__AUTH_MANAGER
            value: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
          - name: AIRFLOW__CORE__INTERNAL_API_URL
            value: "http://airflow-webserver-service.nexusml.svc.cluster.local:8080/api/v1/internal"
          - name: AIRFLOW__WEBSERVER__BASE_URL
            value: "http://airflow-webserver-service.nexusml.svc.cluster.local:8080"
          - name: AIRFLOW__WEBSERVER__WEB_SERVER_HOST
            value: "0.0.0.0"

          # MinIO
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: MINIO_ROOT_USER
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: MINIO_ROOT_PASSWORD
          - name: MINIO_ENDPOINT
            value: "http://minio-service.nexusml.svc.cluster.local:9000"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://minio-service.nexusml.svc.cluster.local:9000"
        envFrom:
          - secretRef:
              name: airflow-secret
        volumeMounts:
          - name: airflow-dags
            mountPath: /opt/airflow/dags
          - name: airflow-logs
            mountPath: /opt/airflow/logs
          - name: airflow-config
            mountPath: /opt/airflow/config/airflow.cfg
            subPath: airflow.cfg
          - name: airflow-plugins
            mountPath: /opt/airflow/plugins
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-config
          configMap:
            name: airflow-config
        - name: airflow-plugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pvc