apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  namespace: nexusml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      securityContext:
        runAsUser: 50000
        runAsGroup: 0
      containers:
      - name: airflow-triggerer
        image: nbngoc1303/airflow-image:latest
        imagePullPolicy: Always
        command: ["airflow", "triggerer"]
        env:
        # --- THÊM DÒNG NÀY ---
        - name: AIRFLOW__CORE__AUTH_MANAGER
          value: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"

        # --- 2. Cấu hình MinIO/S3 ---
        # A. TRUYỀN ACCESS KEY (Tên biến trong Pod: MINIO_ACCESS_KEY)
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER 
        
        # B. TRUYỀN SECRET KEY (Tên biến trong Pod: MINIO_SECRET_KEY)
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD 

        # C. TRUYỀN ENDPOINT (Dùng cho code DAG)
        - name: MINIO_ENDPOINT
          value: "http://minio-service.nexusml.svc.cluster.local:9000"
          
        # --- 3. Cấu hình MLflow (Quan trọng) ---
        # Đảm bảo MLflow biết cách kết nối với MinIO
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio-service.nexusml.svc.cluster.local:9000"

        envFrom:
        - secretRef:
            name: airflow-secret
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        - name: airflow-config
          mountPath: /opt/airflow/config/airflow.cfg
          subPath: airflow.cfg
        - name: airflow-plugins
          mountPath: /opt/airflow/plugins
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: airflow-config
        configMap:
          name: airflow-config
      - name: airflow-plugins
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc
