apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: nexusml
data:
  # Cấu hình chung cho Airflow
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags
    plugins_folder = /opt/airflow/plugins
    base_log_folder = /opt/airflow/logs
    
    [webserver]
    authenticate = True
    auth_backend = airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
    
    [scheduler]
    dag_dir_list_interval = 30
    
    [celery]
    worker_concurrency = 16
    
    [api]
    auth_backend = airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
